### PR TITLE
clementine and protobuf

### PR DESCRIPTION
**Pull request by vdemir**

### CODE REVIEW

**Comment by vdemir** [comment]
Clementine is dependent the libprotobuf.so.10 but it needs libprotobuf.so.8 from protobuf.

**Comment by vdemir** [comment]
Clementine is dependent libprotobuf.so.10 but it needs libprotobuf.so.8 from protobuf according to revdep-revbuild.

**Comment by vdemir** [comment]
Clementine is dependent libprotobuf.so.10 but it needs libprotobuf.so.8  according to revdep-revbuild.

**Comment by aydemir** [comment]
vdemir pr ın merge olmuyor clonun güncel diil sanırım

**Pull request closed without merging**
